DROP DATABASE IF EXISTS scalian; 
CREATE DATABASE IF NOT EXISTS scalian;

USE scalian;

CREATE TABLE IF NOT EXISTS movements (
	key_movement VARCHAR(80) NOT NULL,
	entity VARCHAR(15) NOT NULL,
	internal VARCHAR(1) NOT NULL,
	sourceSystem VARCHAR(15) NOT NULL,
	product VARCHAR(15) NOT NULL,
	movementId VARCHAR(30) NOT NULL,
	contract INT NOT NULL,
	deal_id INT NOT NULL,
	contract_link INT NOT NULL,
	isin VARCHAR(30) NULL,
	typology VARCHAR(50) NULL,
	bs VARCHAR(1) NOT NULL,
	reportDate DATE NOT NULL,
	maturity DATE NOT NULL,
	amount FLOAT NOT NULL,
	amountSent FLOAT NOT NULL,
	amountSettled FLOAT NOT NULL,
	status_mvt VARCHAR(15) NOT NULL,
	account_mvt VARCHAR(50) NOT NULL,
	currency VARCHAR(5) NOT NULL,
	desk VARCHAR(50) NOT NULL,
	portfolio VARCHAR(20) NOT NULL,
	risk_segment VARCHAR(50) NOT NULL,
	countepart VARCHAR(30) NOT NULL,
	flow_tp VARCHAR(5) NOT NULL, 
	trade_date DATE NOT NULL,
	index_mvt VARCHAR(20) NOT NULL,
	instrument VARCHAR(20) NULL,
	fix_var_interest VARCHAR(15) NULL,
	source_process VARCHAR(20) NOT NULL,
	isOpen VARCHAR(20) NOT NULL,
	created DATE NOT NULL,
	target VARCHAR(20) NOT NULL,
	PRIMARY KEY (key_movement)
);

CREATE TABLE IF NOT EXISTS aggregations (
	key_aggregation VARCHAR(80) NOT NULL, 
	entity VARCHAR(15) NOT NULL,
	internal VARCHAR(1) NOT NULL,
	product VARCHAR(30) NOT NULL,
	currency VARCHAR(5) NOT NULL,
	bs VARCHAR(1) NOT NULL,
	desk VARCHAR(30) NOT NULL,
	portfolio VARCHAR(30) NOT NULL,
	risk_segment VARCHAR(30) NULL,
	counterpart VARCHAR(10) NULL,
	typology VARCHAR(30) NOT NULL,
	statusLiq VARCHAR(20) NOT NULL,
	isin VARCHAR(20) NOT NULL,
	maturity DATE NOT NULL,
	dTotal FLOAT NOT NULL,
	settledTotal FLOAT NOT NULL,
	operationType VARCHAR(1) NOT NULL,
	created DATE NOT NULL,
	lastUpdate DATE NOT NULL, 
	source_process VARCHAR(15) NOT NULL,
	isOpen VARCHAR(5) NOT NULL,
	isTotalCash BOOL NOT NULL,
	account_agg VARCHAR(50) NOT NULL,
	target VARCHAR(15) NOT NULL,
	PRIMARY KEY (key_aggregation)
);